### ISSUE TITLE
apk

### ISSUE THREAD

**Issue by DrKinSlayeR** [IrosTheBeggar/mstream-flutter#1]
Thanks for your work !
How i Can compile this version ? With the other i have the wtf error :(

**Comment by IrosTheBeggar** [comment]
I put an apk on the release page:

https://github.com/IrosTheBeggar/mstream-flutter/releases/tag/v0.0.1

**Comment by IrosTheBeggar** [comment]
There's a working release on their now

**Comment by DrKinSlayeR** [comment]
Thanks !
