### ISSUE TITLE
Android 4.0 support

### ISSUE THREAD

**Issue by floviolleau** [IrosTheBeggar/mstream-flutter#2]
Hi,

Thanks for this very good software (mstream) and ecosystem.

I would like to use this android mobile application in my car but the  android embedded in the car system (I cannot upgrade it) is under  android 4.0.X.

Any chance to make it compatible by lowering the minSdkVersion to 15?

Thanks

**Comment by IrosTheBeggar** [comment]
Thanks for checking out mStream.  Unfortunately Flutter needs a minimum of version 16: https://stackoverflow.com/questions/48802841/minimum-android-version-with-flutter
