### ISSUE TITLE
Please update versionCode and versionName

### ISSUE THREAD

**Issue by IzzySoft** [IrosTheBeggar/mstream-flutter#4]
Currently, all your APKs seem to have the very same versionName and versionCode. For example, from the v0.5 tag:

    package: name='mstream.music' versionCode='1' versionName='0.0.1' platformBuildVersionName='0.0.1'

That makes it impossible for Android to detect updates (which would be rejected as "already installed"). Could you please take care to update the two values accordingly?

* versionCode: integer. You can e.g. use it as a "counter" – so v0.5 would have versionCode 5.
* versionName: what's shown to the user. For tag v0.5 I'd e.g. recommend "0.5".

If possible, please already replace the v0.5 APK – otherwise, start with the next release. As you use dynamic versioning (variables), the places to fix it are lines 22 & 27 of `android/app/build.gradle` (as of this writing).

Thanks in advance!

**Comment by IrosTheBeggar** [comment]
@IzzySoft 

This has been fixed on v0.7

**Comment by IzzySoft** [comment]
Thanks! And [here you go](https://apt.izzysoft.de/fdroid/index/apk/mstream.music): Your app can now be installed (and kept up-to-date) using the [F-Droid](https://f-droid.org/) client if my repo was added.

**Comment by IzzySoft** [comment]
Assuming it stays fixed (i.e. you remember updating the two with each new release), I assume we can close this. Thanks again!

PS: For background, just [linking the original request](https://gitlab.com/IzzyOnDroid/repo/issues/55).
